### ISSUE TITLE
Crear gráfico de perfiles.

### ISSUE THREAD

**Issue by pabloolivaresdev** [pabloolivaresDW/ProyectoDW#1]
Crear los graficos de los perfiles, el que acompaña a la ventana de windguru, en caso de dudas revisar el prototipo, debe ser algo con javascript y JSON, no creo que sea muy dificil.

**Comment by pabloolivaresdev** [comment]
Ingreso de perfiles.

**Comment by ghost** [comment]
Creador de de Gráficos listo, realizado con base datos de pruebas personal
